- .travis.yml
- README.md
- setup.py
- tox.ini
This started out as a plan to support Django 1.7 and 1.8, and on all
current versions of Python. This turned into supporting Django 1.8 on
Python 2.7, 3.3, and 3.4 only.
The tests don't pass under Django 1.7 because 1.8 introduced new
settings for configuring templates. Because of this the install_requires
section of setup.py declares that it must be using Django 1.8+.
Python 3.3 support was added, since that's a supported version of Python
under Django 1.8.
Also added pytest-xdist to the tox dependencies, to support running
tox -e py34 -- -f
in order to have it watch and rerun the tests in development.
> More clearly define support

- setup.py
- tests/django_test_setup.py
- tox.ini
This has tox running two tests per box, in tox. It's good for now, but we may want to adjust that in the future to make them all run on their own run from the Travis build matrix.
> Add Django 1.7 to the build matrix

- setup.py
setup.py does not set the `Framework :: Django` classifier which makes it less discoverable by potential new users.
> Add Django classifier to PyPI

- django_components/component.py
- django_components/templatetags/component_tags.py
- tests/templates/incrementer.html
- tests/templates/parent_template.html
- tests/templates/parent_with_args_template.html
- tests/templates/variable_display.html
- tests/test_component.py
- tests/test_context.py
Hey, sorry to drop a bunch of changes on you, but I encountered an issue, had to dig in deep to figure out what was going on, and then needed to change a bunch of stuff to fix my bug.  Here's an overview:
My original problem came when I tried to pass an object as a variable into a `component_block` tag, then have the context method process it into a handful of context variables.  Long story short, this wasn't working, because the context method sometimes gets called twice, with the outputs of the first call being the inputs of the second call.  That works fine if the context method doesn't transform its arguments, but fails when the context variables are different than the component params.
My fix was essentially just to have a single place for calling the context method (in the …
> Rework of context handling

- django_components/component.py
- django_components/templatetags/component_tags.py
- tests/test_templatetags.py
One more minor bug that I ran across.  If you have two `component_block` tags in the same template, and the second doesn't have any slots, you get a key error--the first tag adds the COMPONENT_CONTEXT_KEY subdict to the context, but nothing ever adds the second component as a key to the subdict before the render method tries to look that key up.
> Minor bugfix

- README.md
- django_components/component.py
- django_components/templatetags/component_tags.py
- tests/test_component.py
- tests/test_context.py
- tests/test_registry.py
Hi Emil,
I've been getting a ton of use out of this library and have come up with a few suggestions based on the rough patches that I've encountered.  This PR is focused on giving users more control over how the component can access the outer context, and also adding flexibility in how arguments are passed to the component.  I have a couple other ideas that aren't quite camera-ready... I'll mention them at the end of this.
This is a pretty large block of changes, so here's what's going on in detail:
* Both `component_block` and `component` now allow the user to decide whether or not the component should be able to access the outer context.  The syntax is modelled on the syntax for the [include tag in base Django](https://docs.djangoproject.com/en/3.1/ref/templates/builtins/#include): by …
> Outer context modifications

- django_components/component.py
- tests/test_templatetags.py
I'm embarrassed to report that my last PR interferes with Django's test instrumentation.  Specifically, if you try to use the `assertTemplateUsed` test assertion for `{% component %}`-rendered templates, it will fail (and the `assertTemplateNotUsed` assertion could pass erroneously).  I don't think this was ever working 100% right for `{% component_block %}`, but moving regular component renders from being a simple tag to using the `Component.render()` method has made them also not work properly.
The root cause is that the TemplateUsed/NotUsed assertions are driven by calls to `Template.render()` (which is a wrapper around `Template._render()`.  For `TestCase` (but not `SimpleTestCase`), Django monkey-patches `Template._render()` to emit a signal every time that method is called, which …
> Fixing bug in last PR

- benchmarks/component_rendering.py
- django_components/component.py
- django_components/templatetags/component_tags.py
- tests/test_component.py
- tests/test_performance.py
Hi Emil,
This one is mostly a performance tweak.  In the current version, a new nodelist gets built from the template every time `Component.render()` is called.  However, nothing in the nodelist should change from render to render in terms of the nodes that are built from the component template and any slots that are passed.*  That suggests that you can save some cycles by moving the nodelist compilation out of the render cycle and into the template compilation phase.  That's what I've done here.
* Strictly speaking, this is not true if the template is being dynamically selected based on the context.  If that's an important use-case to keep supporting, then this won't work.
I added a very simplistic "benchmark" that just renders a template a bunch of times.  It showed about a 50% speedup …
> Change time for compilation of component nodelist

- django_components/component.py
- tests/test_component.py
This adds a simple class decorator to fix https://github.com/EmilStenstrom/django-components/issues/31. Basically this:
```
from django_components import component
@component.register("my-component")
class MyComponent(component.Component):
...
```
> Class decorator and test

- .github/workflows/publish-to-pypi.yml
- README.md
This pr adds a github action file to automatically publish tagged releases to PyPI server. fixes #69
> Add a github action to automate releases to PyPI

- pyproject.toml
- setup.cfg
There were duplicated config for isort in two files, this PR merge them into pyproject.toml
> Move duplicated isort config from setup.cfg to pyproject.toml

- README.md
Perhaps fixing an example. Does the js end up in the head even when the component_js_dependencies is at the end of the body?
> Aligning component js with html in example

- README.md
- sampleproject/components/calendar/calendar.js
because {% component_js_dependencies %} loads all the components regardless
fix #163
> 🐛Prevent potential null elements

- README.md
The docs say to set `autodiscovery: False` in `settings.COMPONENTS` to disable autodiscovery, but in the `app_settings` code the field is called `autodiscover`.
Cheers!
> (Docs) Fix param name of autodiscovery -> autodiscover

- README.md
- django_components/__init__.py
- django_components/app_settings.py
- django_components/component.py
- django_components/templatetags/component_tags.py
- pyproject.toml
- setup.cfg
- tests/django_test_setup.py
- tests/templates/slotted_component_nesting_template_pt1_calendar.html
- tests/templates/slotted_component_nesting_template_pt2_dashboard.html
- tests/templates/slotted_template.html
- tests/templates/slotted_template_with_missing_variable.html
- tests/templates/slotted_template_with_required_slot.html
- tests/templates/template_with_conditional_slots.html
- tests/templates/template_with_if_elif_else_conditional_slots.html
- tests/templates/template_with_illegal_super_recursion.html
- tests/templates/template_with_negated_conditional_slots.html
- tests/templates/template_with_nonunique_slots.html
- tests/test_component.py
- tests/test_context.py
- tests/test_templatetags.py
(Breaking) changes to library usage:
- Component blocks pass content to component slots using a new `{% fill %}` tag.
- The meaning of the original `{% slot %}` tag is stricter: it now serves only to declare/open new slots in component templates.
Code changes:
- First crack at updating the documentation. It's not 100% ready.
- All tests updated to use `{% fill %}` where appropriate.
- New tests added to demonstrate component nesting.
- Unsure if correct: replaced the traversal of the node tree in _Component.get_processed_template()_ with a call to a rewritten _find_slot_nodes()_ method.
- Renamed some variables for greater clarity.
Potential future work in context of PR:
- As discussed in linked issue, `{{ slot.super }}`needs to be revised.
- Add `optional` modifier to slot tag. (Low …
> Add `{% fill %}` tag as described in #133 

- django_components/safer_staticfiles/apps.py
Ignore also _.pyc_ files when running `collectstatic` (compiled Python files inside `__pycache__` folder).
Related to https://github.com/EmilStenstrom/django-components/pull/261.
> ignore .pyc files in collectstatic management command

- django_components/middleware.py
This pull request updates the script tag that's placed by django-components in order to render component dependencies. Currently, the script tag is not valid and ends up causing errors in the console and breaking the next script that's defined.
This is currently the largest event in our brand new Sentry front-end setup, so I feel as if it might grow in production 😅
> Use valid script tag HTML to avoid console errors

- README.md
- django_components/component.py
- django_components/component_registry.py
- django_components/middleware.py
- django_components/templatetags/component_tags.py
- sampleproject/components/calendar/calendar.html
- sampleproject/components/todo/todo.html
- tests/templates/template_with_default_and_required_slot.html
- tests/templates/template_with_default_slot.html
- tests/templates/template_with_if_elif_else_conditional_slots.html
- tests/test_templatetags.py
This PR adds default slot filling as described in #231.
Here's an example (copied from the updated docs):
The template:
```htmldjango 
<div class="calendar-component">
<div class="header">
{% slot "header" %}Calendar header{% endslot %}
</div>
<div class="body">
{% slot "body" default %}Today's date is <span>{{ date }}</span>{% endslot %}
</div>
</div>
```
Including the component (notice how the `fill` tag is omitted):
```htmldjango
{% component_block "calendar" date="2020-06-06" %}
Can you believe it's already <span>{{ date }}</span>??
{% endcomponent_block %}
```
The rendered result (exactly the same as before):
```html
<div class="calendar-component">
<div class="header">
Calendar header
</div>
<div class="body">
Can you believe it's already <span>2020-06-06</span>??
</div>
</div>
``` …
> Implement #231 – default slot filling

- README.md
Hi! I found a small error in the `README.md`, nothing very important, but I think it will be helpful to newbies.
> fix: `endfill` instead of `endslot` in README.md

- django_components/middleware.py
- tests/test_dependency_rendering.py
- Fix the COMPONENT_COMMENT_REGEX to find component names with special symbols.
- Fix the test to catch the error.
Follow-up of e0c29e5 and ref: #262
> Add support for - and / in component names in middleware

- django_components/templatetags/component_tags.py
Hi @EmilStenstrom,
I was checking issue #300 and it looks like there's a quick fix.
There's a function called [handle_extendsnode](https://github.com/django-compressor/django-compressor/blob/939499ecca8886b3192da1343f20b30ab248baa4/compressor/offline/django.py#L20) in **django-compressor**, that creates a copy of the node tree replacing the block tags with the nodes of the children blocks.
During that process the `nodelist` is replaced [here](https://github.com/django-compressor/django-compressor/blob/939499ecca8886b3192da1343f20b30ab248baa4/compressor/offline/django.py#L84). But looks like those changes are compatible with **django-components**.
I did this small change, tested the results in an example provided by @spapas, and it looks like things are working well. Also, all tests are …
> Fix for issue with django-compressor

- django_components/component.py
- django_components/template_loader.py
- sampleproject/components/calendar/calendar.py
- sampleproject/components/urls.py
- tests/components/multi_file/multi_file.html
- tests/components/multi_file/multi_file.py
- tests/components/single_file.py
- tests/components/urls.py
- tests/test_autodiscover.py
Hey @EmilStenstrom @Fingel,
I got a working version of a fix for issue #368. There was a quick fix (but @EmilStenstrom you might not be its biggest fan 😅). The hardest part was getting tests that replicated the issue, but I now have a version that seems to achieve that.
@Fingel your research was very useful to understand where the issue originated. Thank you very much.
When Django [initializes](https://docs.djangoproject.com/en/5.0/ref/applications/#initialization-process) the application registry, for each application in `INSTALLED_APPS` Django imports the root package of the application.
For `django-components`, this means the `ready` method is called which then calls `autodiscover`, as pointed by Fingel. `autodiscover` looks for all the locations of components and then executes those …
> Fix issue #368 and add tests

- README.md
- django_components/template_loader.py
Fixes #381
I went through all usages of BASE_DIR in the project and made sure all of them are safe for strings. Didn't touch sampleproject which still defined BASE_DIR as a Path.
> Don't rely on BASE_DIR being a Path.

- README.md
- django_components/__init__.py
- django_components/component.py
- django_components/logger.py
- django_components/template_loader.py
- django_components/utils/autodiscover.py
- sampleproject/components/calendar/calendar.py
- sampleproject/components/nested/calendar/calendar.css
- sampleproject/components/nested/calendar/calendar.html
- sampleproject/components/nested/calendar/calendar.js
- sampleproject/components/nested/calendar/calendar.py
- sampleproject/components/urls.py
- sampleproject/sampleproject/settings.py
- tests/components/relative_file/relative_file.css
- tests/components/relative_file/relative_file.html
- tests/components/relative_file/relative_file.js
- tests/components/relative_file/relative_file.py
- tests/django_test_setup.py
- tests/test_autodiscover.py
- tests/test_component.py
- tests/test_context.py
Here is the first go at supporting relative imports for template and media files (See https://github.com/EmilStenstrom/django-components/issues/380). Relative import means that, when we define a component with a template and/or media files, then we can specify import path relative to the directory where the component class is defined.
So instead of specifying the import path relative to the Django's templates dirs, e.g.:
```py
@component.register("button")
class Button(Component):
template_name = "module_name/components/component_name/component_name.html"
class Media:
js = "module_name/components/component_name/component_name.js"
css = "module_name/components/component_name/component_name.css"
```
We can shorten it to:
```py
@component.register("button")
class Button(Component): …
```
> feat: resolve media and template files relative to component class dir

- django_components/component.py
- django_components/component_registry.py
Hey :wave:
I noticed in my project that mypy (in strict mode) was complaining that the `@component.register` decorator was untyped:
```
Call to untyped function "register" in typed context  [no-untyped-call]
```
I went ahead and typed the decorator, as well as the rest of the `component_registry` module.
I can scale back the changes to only type the decorator if needed.
Please let met know if you'd be interested in some help for the package, notably around type hints, CI or packaging, I'd be happy to contribute.
Thanks!
> fix: type component registry

- src/django_components/component.py
Closes https://github.com/EmilStenstrom/django-components/issues/414
The issue was with Context, turns out that the context_data in component.Component.render may already be an instance of Context, so a simple check for that fixed it for me.
I also updated the input for `_process_template_and_update_filled_slot_context`, so we're not passing in Django's Context, since it wasn't necessary, so there's less touchpoints with it.
> fix: avoid nested django contexts when rendering

- README.md
- src/django_components/component.py
- src/django_components/middleware.py
- src/django_components/slots.py
- src/django_components/templatetags/component_tags.py
This is part of work towards https://github.com/EmilStenstrom/django-components/issues/350.
Initially I had hard time understanding how the slots work, so I wanted to make it easier by making it clearer where the slots logic lives by moving it to a separate file and documenting it a bit.
> refactor: move slots logic to own file

- .github/workflows/tests.yml
- README.md
- pyproject.toml
- scripts/supported_versions.py
- setup.py
- tox.ini
Hey :wave: 
Following the recent packaging changes, I propose to go a step further and move to pyproject.toml, to use more modern Python packaging tooling.
This change will enable us to use any modern build-system, like recent `setuptools`, `pdm-backend` `hatchling`, which supports plugins. This could be useful to set the version automatically from the Git tag for example.
Unfortunately, Python 3.6 being no longer supported, I had to drop its support. I opened an issue #418 to discuss Python support policy.
> build: move to PEP517 and pyproject.toml, drop support for Py3.6 and Py3.7

- src/django_components/app_settings.py
- tests/test_settings.py
Hey @JuroOravec @EmilStenstrom,
Sorry about issue #421, my bad. I tested that the [feature worked](https://github.com/EmilStenstrom/django-components/blob/84db2b7314a5bccc83b3854e81316c42a157d59c/tests/test_context.py#L332), but didn't even think of testing setting the context behavior value. Couldn't imagine I'd get that part wrong haha.
I've been swamped these days, but thought of making a small PR to fix the issue based on what Juro mentioned.
I added a small test for the setting and tested it worked in the sample project (but didn't commit that last part).
P.S. All the stuff you've been adding to the library lately is amazing! Super cool. Feels like it's picking up steam.
> Fix issue #421

- README.md
Fixes #426 
In the example calendar component this is what changed:
- css file name to`style.css` and the `css` variable in the `Media` class to `calendar/style.css`
- js file name to `script.js` and the `js` variable in the `Media` class to `calendar/script.js` 
- the `template_name`variable to `calendar/template.html`
- replaced the file structure screenshot with a file tree with the above files
- updated comments referencing this files
> fix: inconsistent file names in README.md

- src/django_components/component.py
- tests/test_component.py
Fix the issue identified in https://github.com/EmilStenstrom/django-components/discussions/425 by using `sys.modules` to obtain the path to the file where a component class was created.
> refactor: use sys.modules to get component file path

- README.md
- src/django_components/__init__.py
- src/django_components/component.py
- src/django_components/utils.py
- tests/test_autodiscover.py
Fixes https://github.com/EmilStenstrom/django-components/issues/431
This was a lot of trial and error, but it seems that by using `importlib.import_module(module_name)`, we don't have to interact with the `sys.modules`. Instead, we just pass it a python import like `"myapp.components.calendar"`. And so, there are no conflcts with 3rd party libraries anymore.
I wonder what would be a good way to test this:
- I tried adding a `django.py` to one of the `test_structures` (e.g. `tests/test_structures/test_structure_1/components/django/django.py`), but it didn't get picked up.
- I checked if things worked or not by having a `django.py` component in the sampleproject (`sampleproject/components/django/django.py`). That worked, but don't know if we want to use the demo project for testing.
- I was …
> refactor: fix clash with autodiscovery

- README.md
- benchmarks/component_rendering.py
- pyproject.toml
- scripts/supported_versions.py
- tests/test_autodiscover.py
- tests/test_component.py
- tests/test_component_as_view.py
- tests/test_context.py
- tests/test_dependency_rendering.py
- tests/test_settings.py
- tests/test_templatetags.py
- tests/testutils.py
- tox.ini
While I was hacking away at tests for https://github.com/EmilStenstrom/django-components/issues/436, I had some strange error with Django 3.2. That got me searching, and along the way, I stumbled across the [Django download page](https://www.djangoproject.com/download/), which says that Django 3.2, 4.0, and 4.1 are no longer supported.
Support policy was recently discussed in https://github.com/EmilStenstrom/django-components/issues/418#issuecomment-2028479587, based on which I think we can drop these versions.
One other thing I noticed was that the `supported_versions` script still included v3.2-4.2 in the generated text. This is because it took the data from the table at https://docs.djangoproject.com/en/dev/faq/install/, which lists even unsupported Django versions. So instead I …
> chore: Drop support for Django 3.2, 4.0, 4.1

- src/django_components/middleware.py
Hi,
PR for converting the middleware to async as mentioned here (https://github.com/EmilStenstrom/django-components/issues/464)
This is working fine for me both sync and async via Daphne.
> feat: Support both sync and async in ComponentDependencyMiddleware

- README.md
- docs/slot_rendering.md
- sampleproject/sampleproject/settings.py
- src/django_components/app_settings.py
- src/django_components/component.py
- src/django_components/context.py
- src/django_components/logger.py
- src/django_components/node.py
- src/django_components/slots.py
- src/django_components/templatetags/component_tags.py
- tests/templates/template_is_filled.html
- tests/templates/template_with_conditional_slots.html
- tests/templates/template_with_if_elif_else_conditional_slots.html
- tests/templates/template_with_negated_conditional_slots.html
- tests/templates/template_with_nonunique_slots_nested.html
- tests/test_component.py
- tests/test_context.py
- tests/test_templatetags.py
This MR:
- Removes the nodes and template tags involved in the If/Elif/Else logic (`{% if_filled %}`, etc). Instead, the context is populated with a slots dict that tracks which slots have been filled, and can be used like `{% if component_vars.is_filled.<slot_name> %}`
- Merges `context_behavior` and `slot_context_behavior` into `context_behavior`. It now has two options - `"isolated"` and `"django"` (this was previously called `global`). `isolated` is the default.
- Revamps the slot resolution logic. It has now been moved "upstream", meaning that the slot resolution is now done in `Component.render()`. And so, by the time we reach `SlotNode.render()`, we only need to look up the corresponding slot fill.
- To make it easier to onboard people to the slot resolution flow, I've documented …
> feat: merge context settings, replace if_filled tag with var

- docs/slots_and_blocks.md
- src/django_components/component.py
- src/django_components/node.py
- src/django_components/slots.py
- tests/templates/block_in_slot_in_component.html
- tests/templates/block_inside_component.html
- tests/templates/extendable_template_with_blocks.html
- tests/templates/slot_inside_block.html
- tests/templates/slot_inside_extends.html
- tests/templates/slot_inside_include.html
- tests/test_templatetags.py
Added tests to explore behavior of components with "loader tags" (`extends`, `include`, `block`). Tested out all combinations I could think of:
- Slots inside `include`
- Slots inside `extends`
- Slots inside `block`
- Block inside `slot`
Surprisingly, it all mostly worked as expected 😄, and I had to update only the traversal logic, so it could extract nodes from `extends` / `include` tags.
Closes https://github.com/EmilStenstrom/django-components/issues/134
> fix: loader tags compatibility

- tests/test_component_as_view.py
This PR inlines all the tests in tests/test_component_as_view.py with the purpose of making each test be self-contained. This means the component, registration, and the views, are all defined in the same function. Let me know what you think of the structure.
> Inline component view tests

- README.md
- src/django_components/template_parser.py
- src/django_components/templatetags/component_tags.py
- tests/test_template_parser.py
Part of https://github.com/EmilStenstrom/django-components/discussions/471
This MR allows us to use component argument keys with special characters `# @ - . :`.
The parsing logic override is based on [django-slippers implementation](https://github.com/mixxorz/slippers/blob/main/slippers/template.py)
> feat: support special chars `# @ - . :` in component kwargs

- src/django_components/template_loader.py
- tests/test_autodiscover.py
fixes #476  
Hoping to fix issue [here](https://github.com/EmilStenstrom/django-components/issues/476)
I suggested to use `logger.warning` and simply not to consider the _STATICFILES_DIR_ value if the value is incorrect. But depends on your preference.
> fix: make template_loader consider tuples for STATICFILES_DIRS

- src/django_components/component.py
- https://github.com/EmilStenstrom/django-components/issues/458
As asked by @EmilStenstrom I'm making this small contribution
```
"register" is not exported from module "django_components.component" [reportPrivateImportUsage] 
```
--- 
Tested also output in `pyright` lsp and it is happy too:
Before:
After:
> feat: alias component_registry imports for mypy

- README.md
- src/django_components/component.py
- src/django_components/slots.py
- src/django_components/templatetags/component_tags.py
- tests/test_templatetags.py
Change the API for accessing slot's default content from
```django
{% fill "my_slot" as "alias" %}
{{ alias.default }}
{% endfill %}
```
to
```django
{% fill "my_slot" default="slot_default" %}
{{ slot_default }}
{% endfill %}
```
Closes #502
> refactor: change fill alias from "as var" to default=var

- src/django_components/attributes.py
- tests/test_attributes.py
Addresses this issue: https://github.com/EmilStenstrom/django-components/issues/512
> fix: typo in html_attrs defaults dict fetching

- README.md
- src/django_components/app_settings.py
Change the default `context_behavior` setting to "django", and update README.
Closes https://github.com/EmilStenstrom/django-components/issues/498
> refactor: change context_behavior default to "django"

- README.md
- sampleproject/components/greeting.py
- src/django_components/component.py
- src/django_components/component_registry.py
- src/django_components/node.py
- src/django_components/slots.py
- tests/test_component.py
- tests/test_component_as_view.py
- tests/test_component_media.py
Initial implementation for https://github.com/EmilStenstrom/django-components/issues/520.
See individual comments for details.
What still remains is to do:
Closes #520
> feat: refactor render fn and allow slots as functions

- README.md
- sampleproject/.gitignore
- sampleproject/README.md
- sampleproject/requirements.txt
- sampleproject/sampleproject/settings.py
- src/django_components/safer_staticfiles/apps.py
- tests/components/safer_staticfiles/safer_staticfiles.css
- tests/components/safer_staticfiles/safer_staticfiles.html
- tests/components/safer_staticfiles/safer_staticfiles.js
- tests/components/safer_staticfiles/safer_staticfiles.py
- tests/test_autodiscover.py
- tests/test_component_media.py
- tests/test_safer_staticfiles.py
Small change as a result of https://github.com/EmilStenstrom/django-components/issues/536:
- Add tests for `safer_staticfiles`
- Document behavior of `safer_staticfiles` for prod vs dev servers.
- Update sampleproject to show how to handle static files for dev/prod deployments
> refactor: usage notes + tests for safer_staticfiles

- src/django_components/attributes.py
- src/django_components/component.py
- src/django_components/context.py
- src/django_components/slots.py
- tests/test_attributes.py
- tests/test_component.py
- tests/test_templatetags_provide.py
- tests/test_templatetags_slot_fill.py
I came across these errors when upgrading from django-components v0.73 to v0.82:
- fix: Do not escape already escaped slots when slots are given to `slots` kwarg in `Component.render`
- fix: html_attrs allow `attrs` and `defaults` to be `None`
- fix: slots inside `{% provide %}` should have access to provided values
Also modified the raised errors from inside the components' `render` function, so it shows info on which component (name) raised the error.
> fix: various fixes for inject/provide and html_attrs

- src/django_components/template_parser.py
- tests/test_template_parser.py
We have the feature of "aggregating kwargs", meaning that if I pass following kwarg to a component, `prop:key=value`, then this gets interpreted as "passing kwarg 'prop', which is a dict `{"key": value}`.
As per https://github.com/EmilStenstrom/django-components/discussions/556#discussioncomment-10182903, currently we "aggregate" even component kwargs that start with colon (`:`). These should be ignored.
> fix: do not aggregate kwargs that start with colon

- README.md
- src/django_components/management/commands/upgradecomponent.py
Just tried to run this on my production codebase and ran into this easily reproducible issue:
```
with open(file_path, "r+", encoding="utf-8") as f:
^^^^^^^^^
UnboundLocalError: cannot access local variable 'file_path' where it is not associated with a value
```
Also clarified the verbiage in the README for anyone else updating from an archaic version (maybe I'm the only one), but it took me a bit to realize I point this at my templates, not components dir.
Note that this still didn't get me 100% of the way there, but it went from 0-50 and saved me a ton of time. Still missing lots of opening component_block tags and plenty more {% endcomponent %}.
> Fix upgradecomponent

- README.md
- benchmarks/component_rendering.py
- docs/slots_and_blocks.md
- sampleproject/components/calendar/calendar.py
- sampleproject/components/greeting.py
- sampleproject/components/nested/calendar/calendar.py
- sampleproject/components/todo/todo.py
- src/django_components/__init__.py
- src/django_components/component.py
- src/django_components/component_media.py
- src/django_components/management/commands/startcomponent.py
- tests/components/multi_file/multi_file.py
- tests/components/relative_file/relative_file.py
- tests/components/relative_file_pathobj/relative_file_pathobj.py
- tests/components/safer_staticfiles/safer_staticfiles.py
- tests/components/single_file.py
- tests/test_attributes.py
- tests/test_autodiscover.py
- tests/test_component.py
- tests/test_component_as_view.py
- tests/test_component_media.py
- tests/test_context.py
- tests/test_dependency_rendering.py
- tests/test_registry.py
- tests/test_template_parser.py
- tests/test_templatetags.py
- tests/test_templatetags_component.py
- tests/test_templatetags_provide.py
- tests/test_templatetags_slot_fill.py
- tests/test_templatetags_templating.py
This MR makes 2 changes:
1. Export public API from `__init__.py` (see https://github.com/EmilStenstrom/django-components/pull/562/files#diff-1aa73be263a2679bafabb9bcc26cabafb8d4bfcf77e243fb9e56f44e0835b7be), so users can import them from the top-level of the package, like so:
```py
from django_components import ...
```
2. Update the canonical way of importing the library, so that users don't have to import submodules. This also means that we will have the freedom to update files within the package without breaking the public contract.
Before:
```py
from django_components import component, types
types.django_html
types.css
types.js
component.Component
component.registry
component.register
component.AlreadyRegistered
component.NotRegistered
```
After:
```py
import django_components as dc …
```
> refactor: Use top-level exports as public API

- .gitignore
- README.md
- src/django_components/component_registry.py
- tests/test_attributes.py
- tests/test_context.py
- tests/test_dependency_rendering.py
- tests/test_registry.py
- tests/test_templatetags.py
- tests/test_templatetags_component.py
- tests/test_templatetags_slot_fill.py
- tests/test_templatetags_templating.py
- tests/testutils.py
Changes:
- Document how `ComponentRegistry` works
- `ComponentRegistry()` accepts an optional `library` kwarg
- `@register` decorator accepts an optional `registry` kwarg
- Preparation for custom component template tags:
- There can be multiple template tags used for rendering the same component (for the "block" and "inline" forms)
- When user registers a component with not-seen-before template tags, the tags are automatically registered
into to `library`. And when the last component that uses those tags is unregistered,
the tag is removed from `library`.
This is the last step before https://github.com/EmilStenstrom/django-components/issues/527
> refactor: prepare registry for custom template tags and docs

- src/django_components/attributes.py
- tests/test_attributes.py
Tiny error that I just came across in `{% html_attrs %}` as I upgraded from v0.84 to v0.90.
In v0.84, `html_attrs` allowed `attrs` and `defaults` to be `None`, but it's not the case in v0.90.
> fix: Allow `None` for attrs in `html_attrs` tag

- src/django_components/types.py
The mypy check with Django plugin breaks with the following error:
```
Traceback (most recent call last):
File "mypy/semanal.py", line 7092, in accept
File "mypy/nodes.py", line 819, in accept
File "mypy/semanal.py", line 874, in visit_func_def
File "mypy/semanal.py", line 916, in analyze_func_def
File "mypy/typeanal.py", line 1098, in visit_callable_type
File "mypy/typeanal.py", line 1774, in anal_type
File "mypy/types.py", line 2707, in accept
File "mypy/types.py", line 944, in accept
File "mypy/typeanal.py", line 281, in visit_unbound_type
File "mypy/typeanal.py", line 334, in visit_unbound_type_nonoptional
File "/home/okipa/.local/share/virtualenvs/okipa-lk14Xlau/lib/python3.12/site-packages/mypy_django_plugin/transformers/models.py", line 1067, in handle_annotated_type
type_arg = …
```
> fix: mypy checking with django plugin is broken

- README.md
- src/django_components/__init__.py
- src/django_components/attributes.py
- src/django_components/component.py
- src/django_components/expression.py
- src/django_components/node.py
- src/django_components/provide.py
- src/django_components/slots.py
- src/django_components/template_parser.py
- src/django_components/templatetags/component_tags.py
- tests/test_expression.py
- tests/test_template_parser.py
- tests/test_templatetags_slot_fill.py
Refactor that moves the processing of kwargs passed to template tags from compile- to render-time. 
This is a precursor for the dynamic expressions (https://github.com/EmilStenstrom/django-components/discussions/552), spread operator (https://github.com/EmilStenstrom/django-components/issues/539), and dynamic slots and fills (https://github.com/EmilStenstrom/django-components/issues/587).
> refactor: move kwargs resolution to render-time + cleanup

- .github/workflows/docs.yml
Related to https://github.com/EmilStenstrom/django-components/issues/401#issuecomment-2308379192: I think these changes are at least needed to fix docs deployment to gh-pages.
@EmilStenstrom did you already activate gh-pages in settings of the repo?
> Fix docs deployment to gh-pages.

- tox.ini
Juro has done a great job increasing the test coverage for new code. 
This pull request increases the minimum coverage requirement to 97%. The `coverage report` command has been updated to fail if the coverage falls below this threshold.
> Increase minimum coverage to 97%

- README.md
- src/django_components/expression.py
- src/django_components/templatetags/component_tags.py
- tests/test_expression.py
- tests/test_template_parser.py
Good news, unlike I [said in the discussion](https://github.com/EmilStenstrom/django-components/discussions/552#discussioncomment-10394843) previously, I actually managed to pull off supporting both `{{ }}` and `{% %}` tags (and also `{# #}`)!
Also, after going over how [django-cotton designed it](https://github.com/wrabit/django-cotton#template-expressions-in-attributes), I feel like their approach is more useful than what I proposed initially.
So initially, I was saying that we should allow only a single tag, and no text.
So while this would work:
```django
{% my_component model="{{ model_name }}" %}
```
This would not
```django
{% my_component model="todos.{{ index }}.name" %}
```
But now I think that the latter is more flexible and more can be achieved with it. So the text is …
> feat: add dynamic expressions

- .github/workflows/docs.yml
@EmilStenstrom - At the root of gh-pages there should be an index.html file with the redirect. It is missing here in this repo.
Maybe issue https://github.com/jimporter/mike/issues/188 for mike2.0 was the reason for the missing redirects. This PR applies the suggested change.
> Fix redirect to latest for mike 2.0

- README.md
- src/django_components/component.py
- src/django_components/provide.py
- src/django_components/slots.py
- src/django_components/templatetags/component_tags.py
- tests/test_attributes.py
- tests/test_templatetags_provide.py
- tests/test_templatetags_slot_fill.py
Allow to specify slot and fill names as variables. ...And also for the `provide` tag, since it works the same way.
It would be nice to also have dynamic components, bit I'm leaving that for later, as that one's more complicated because of the TagFormatter.
Closes https://github.com/EmilStenstrom/django-components/issues/587
> feat: dynamic slots, fills, and provides

- index.html
This PR is targeting the gh-pages branch. 
`mike` does obviously not create an index.html file at the root of the gh-pages branch to redirect to latest automatically.
It seem that this file has to be added separately. 
Examples: e.g. a package from the `mike`-author: https://github.com/jimporter/bfg9000/tree/gh-pages (old version of redirect-file) or https://github.com/abhiTronix/vidgear/blob/gh-pages/index.html (new version  of redirect-file from mike 2.0)
> Create root index.html for mkdocs deployed with mike (redirect to latest)

- README.md
- src/django_components/__init__.py
- src/django_components/component.py
- src/django_components/component_registry.py
- src/django_components/context.py
- src/django_components/library.py
- src/django_components/slots.py
- src/django_components/tag_formatter.py
- src/django_components/templatetags/component_tags.py
- tests/test_registry.py
Ngl, I'm pretty excited about this! 🦜 
This MR allows template settings (`CONTEXT_BEHAVIOR` and `TAG_FORMATTER`), to be configured per registry / library.
So, assuming that `simple_a` comes from Library A, and `simple_b` comes from Library B, now following is possible:
```django
{% simple_a variable=123 %}
SLOT 123
{% endsimple_a %}
{% component "simple_b" variable=123 %}
SLOT ABC
{% endcomponent %}
```
Also:
- Added section on `ComponentRegistry` settings
- Added section on writing, publishing and sharing component libraries
Closes https://github.com/EmilStenstrom/django-components/issues/590
TODO:
> feat: allow different template settings for ComponentRegistries

- README.md
- src/django_components/__init__.py
- src/django_components/component.py
- src/django_components/slots.py
- src/django_components/types.py
- src/django_components/utils.py
- tests/test_component.py
As I mention in https://github.com/EmilStenstrom/django-components/issues/622#issuecomment-2316849176, this MR adds validation of args, kwargs, slots, and data (returned from `get_context_data`) based on the types passed to the `Component`'s generics.
The reason I wanted to add this is following:
When I was adding the typing support to the components, I had two options:
1. Either use [`ParamSpec`](https://docs.python.org/3/library/typing.html#typing.ParamSpec) as one of the Component's generics, which would be bound to the `get_context_data`. This way, the `get_context_data` function would have been the source of truth for the type.
2. Or define args and kwargs as I eventually did, as a `Tuple` and `TypedDict`. This way, the `Component.render` would still be correctly typed, but the …
> feat: validate component inputs if types are given

- README.md
- sampleproject/components/calendar/calendar.py
- sampleproject/components/nested/calendar/calendar.py
- sampleproject/components/todo/todo.py
- src/django_components/__init__.py
- src/django_components/component.py
- src/django_components/slots.py
- src/django_components/template.py
- src/django_components/templatetags/component_tags.py
- src/django_components/utils.py
- tests/test_component.py
- tests/test_component_media.py
- tests/test_template.py
- tests/test_templatetags_slot_fill.py
- tests/testutils.py
Changes:
- Reintroduce template caching using the `TEMPLATE_CACHE_SIZE` setting (fixes https://github.com/EmilStenstrom/django-components/issues/589)
- Also caches the process of extracting `{% fill %}` tags from `{% component %}` tags
- Add a way for users to manually add Templates to the cache using `cached_template`
Also relevant API cleanup / changes:
- The undocumented `Component.get_template` is made private as `_get_template`
- Introduced new `get_template`, which works like `get_template_string`, except it can return either a string or a Template instance. And I tagged `get_template_string` to be deprecated and will work till v1.
- Also updated the logic so that all 4 ways of defining the template are mutually exclusive, as previously it was ambiguous which one of e.g. …
> refactor: Fix template caching, expose `cached_template`, Component.template API changes

- .github/workflows/docs.yml
I though I create this PR as long as I remember that the clean-up was planned. The problematic "latest" directory in the `gh-pages` branch was removed in the meantime by running the action. The parameters for the if-cases also work so the debug-part is no longer required.
Maybe wait with merging until the docs are also deployed correctly (settings change mentioned in https://github.com/EmilStenstrom/django-components/issues/650#issuecomment-2334773431).
> Clean up docs action

- tox.ini
I've gone through and made sure we're not including lots of unessesary cruft in the tox.ini, and also added black so that it doesn't just exist in the pre-commit config.
Experimented with adding bandit check but decided against it because it just added lots of false positives.
> Minimize tox config and add black

- README.md
- src/django_components/component.py
- tests/test_component_as_view.py
Currently the logic of middleware that inserts the JS and CSS dependencies works with REGISTERED components only (See https://github.com/EmilStenstrom/django-components/issues/657). This will be soon refactored, but since it'll be a large change, it may be 2 weeks or so. 
To allow to work around this limitation in the meantime, this MR refactors the `Component.as_view()` class method to work similar to `render` or `render_to_response`. That is, if the method is called on an INSTANCE, the component instance is passed. And if the method is called on the CLASS, we create an empty instance.
That way, one will be able to pass a dummy "registered_name" to the component:
```py
MyComponent.as_view()
MyComponent("my_comp").as_view()
MyComponent.as_view()
MyComponent("my_comp").as_view()
```
Part …
> refactor: pass instantiated component to as_view

- src/django_components/app_settings.py
- tests/test_settings.py
This coverts BASE_DIR to a `pathlib.Path`. It works fine if BASE_DIR is already a Path.
> Make sure BASE_DIR is a Path - fixesd #687

- README.md
- Added an example in the component context section demonstrating how to access outer context variables using `self.outer_context`.
- Recommended best practice of explicitly passing variables to components for better code clarity and maintainability.
> Add example for accessing outer context in components and recommend best practices

- pyproject.toml
- src/django_components/dependencies.py
- src/django_components/html.py
- src/django_components/templatetags/component_tags.py
- tests/test_dependency_rendering.py
- tests/test_dependency_rendering_e2e.py
- tests/test_html.py
Some of a cleanup as mentioned here https://github.com/EmilStenstrom/django-components/pull/688#issuecomment-2400732761
Changes:
- Add test for noJS browser (https://github.com/EmilStenstrom/django-components/commit/3ac74d22a77994fa5c75ccf193cdcc7387355d39)
- Remove skipped tests that tested preloading (https://github.com/EmilStenstrom/django-components/commit/2d2ec48b9c2c6b154c277c756691be805ea23f7b)
- Remove leftover code for preloading (https://github.com/EmilStenstrom/django-components/commit/696f027b5298b3e320e20250bb4f57041ab198c8)
- Update selectolax to use Node.insert_child (https://github.com/EmilStenstrom/django-components/commit/20612e2d0e5a2e01bd330a1b148216a377f5295f)
> refactor: selectolax update and tests cleanup

- CHANGELOG.md
- README.md
- benchmarks/component_rendering.py
- src/django_components/component.py
- src/django_components/dependencies.py
- src/django_components/library.py
- src/django_components/templatetags/component_tags.py
- tests/components/relative_file_pathobj/relative_file_pathobj.html
- tests/test_component_media.py
- tests/test_context.py
- tests/test_dependencies.py
- tests/test_dependency_rendering.py
- tests/test_registry.py
More cleanup as originally mentioned here https://github.com/EmilStenstrom/django-components/pull/688#issuecomment-2400732761
This one removes `{% component_dependencies %}`, leaving only the JS- and CSS-specific variants.
See the rationale here https://github.com/EmilStenstrom/django-components/pull/706/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR14
> refactor: remove joint {% component_dependencies %} tag

- src/django_components/templatetags/component_tags.py
- tests/test_template_parser.py
- Documented individual tags like `{% component %}`, `{% slot %}`, and other.
- Refactored the tags so that the parsing of tags inputs (what args, kwargs or flags it accepts) is now declarative. So each tag defines a `TagSpec` instance, which is the source of truth and is also used for generating documentation.
> refactor: Document template tags

- CHANGELOG.md
- src/django_components/component.py
- src/django_components/components/dynamic.py
- src/django_components/slots.py
- tests/test_templatetags_slot_fill.py
As I was updating the docs, I've found 4 bugs, plus did some tweaks. I want to first fix the bugs / push the tweaks, before I finish the docs, so that I won't have to re-visit the docs afterwards.
So when it comes to PRs, my course of actions is to:
1. Fix the bugs
2. Submit the tweaks
3. And only then I will be again making PRs documenting the API with docstrings (like the [last one](https://github.com/EmilStenstrom/django-components/pull/716))
4. After that, it will be possible to make PRs in parallel for both documentation (breaking up and migrating the README)
and the rest of the[ features like JS/CSS vars](https://docs.google.com/document/d/1A9GfJrYHpmbcXUkQfk0wJFmjJyJs5vlfFESWHPb1w-k/edit?usp=sharing), etc.
Bugs:
- `self.input.slots` is empty when component is given slots inside the …
> refactor: pass slot fills in template via slots param

- tox.ini
Turns out that the error was following:
1. When playwright installs a browser, it caches it at
`/home/runner/.cache/ms-playwright/chromium-1140/chrome-linux/chrome`
2. The cache path contains the browser version.
3. Different versions of playwright point to different versions of cache. 
4. When we installed the browser, we did it using `requirements-ci.txt`, which pinned playwright version to `1.47.0`.
5. But when we ran tox, tox has it's own set of dependencies specified, adn there the playwright version was not pinned and used newer version of playwright.
6. And so, inside tox, the latter playwright version was used, which expected browser to be installed inside `chromium-1140`. But we installed the browser using the older playwright version, which installed version `chromium-v1134`.
So …
> refactor: pin version of playwright in tests

- src/django_components/slots.py
- tests/test_templatetags_slot_fill.py
This MR makes it OK if a template contains multiple slots with the same name and flagged as default, e.g.:
```django
{% load component_tags %}
<div>
<main>{% slot "main" default %}1{% endslot %}</main>
<div>{% slot "main" default %}2{% endslot %}</div>
</div>
```
> fix: Do not raise error if multiple slots with same name are flagged as default

- CHANGELOG.md
- src/django_components/tag_formatter.py
- tests/test_tag_formatter.py
For the UI component library I was playing around with the idea of defining component similarly to how Vue / React does it - with PascalCase and forward slash to indicate the end tag:
```django
{% MyComp %}
{% /MyComp %}
```
But the forward slash was not recognized. So this MR adds `/` to the set of character allowed for start / end tags.
Also updated docs for tag formatter API.
> refactor: tag formatter - allow fwd slash in end tag

- CHANGELOG.md
- README.md
- src/django_components/app_settings.py
- src/django_components/component.py
- src/django_components/component_registry.py
- src/django_components/slots.py
- src/django_components/tag_formatter.py
- tests/test_registry.py
In this MR I suggest to rename the inputs passed to ComponentRegistry, from all-uppercase to lowercase. The reason is so that the API is aligned with the global settings, which are also all-lowercase. I noticed this difference when I was writing up the documentation.
The reason why I originally defined the settings as uppercase was because I got confused by our internal `app_settings`, where the fields are defined as upper case.
NOTE: This MR has similar structure as the last one - One commit is the change itself, the other is documentation.
> refactor: Use lowercase names for registry settings

- CHANGELOG.md
- sampleproject/sampleproject/settings.py
- src/django_components/__init__.py
- src/django_components/app_settings.py
- src/django_components/util/misc.py
- tests/test_settings.py
I wanted the settings documentation to live close to the code, using the docstrings to generate the API reference docs. However, the way we parsed the django_component's settings, I wasn't able to access the settings fields. There is the `AppSettings` class, but its fields do not match the fields that the user fills in (e.g. user supplies `app_dirs`, while we access it as `app_settings.APP_DIRS`.
So what I did was to define a class (`ComponentsSettings`) that's purely for defining the shape of the user-facing settings. And this becomes the source of truth of what settings are there. This class can then have its fields documented with docstrings, and this can be then used to generate the settings docs. Plus, it also offers users intellisense and type checking if users decide to use …
> feat: define settings as a data class for type hints, intellisense, and docs

- CHANGELOG.md
- src/django_components/__init__.py
- src/django_components/app_settings.py
- src/django_components/apps.py
- src/django_components/autodiscovery.py
- src/django_components/component_media.py
- src/django_components/finders.py
- src/django_components/template_loader.py
- src/django_components/util/loader.py
- src/django_components/util/misc.py
- tests/test_autodiscover.py
- tests/test_finders.py
- tests/test_loader.py
This MR is a mix of a couple of changes, it grew a bit out of scope, sorry about that.
Initially I wanted to only rename the settings:
- `forbidden_static_files` -> `static_files_forbidden`, so it's aligned with `static_files_allowed`
- `reload_on_template_change` -> `reload_on_file_change`, because using the word "template" suggests that this would apply only to HTML files.
Similarly to the last MR, the old names of the settings are kept, but tagged as deprecated, and would be removed in v1.
Moreover, the reload-on-change feature (`reload_on_template_change`) wasn't working, so I wanted to fix that. But for that I needed to obtain the same list of directories as we use in `autodiscover()`.
Moreover, for django_vue, I also need to access the same list of directories, so I can search them …
> refactor: fix reload-on-change logic, expose autodiscover's dirs-getting logic, rename settings

- README.md
This PR improves the first example the user sees to be easier to understand. I removed the references to JS/CSS to keep things simple.
> Improve first example the users sees

- src/django_components/templatetags/component_tags.py
- src/django_components/util/tag_parser.py
- tests/test_tag_parser.py
- tests/test_templatetags.py
To support the use of Django template tags inside component inputs, e.g.
```django
{% component
display_name="{{ first_name }} {{ last_name }}"
description="{% lorem w 3 %}"
/ %}
```
We have to fix Django's tokenization, because Django simply cuts up the template based on the first found `{% ... %}` pairs. So, in the example above, even though the `{% lorem w 3 %}` is wrapped by quotes, Django wrongly interprets the `{% component %}` tag to be:
```django
{% component
display_name="{{ first_name }} {{ last_name }}"
description="{% lorem w 3 %}"
```
When Django cuts up a tag incorrectly like above, we can identify it because there's a missing closing quote (`"`).
But the fix I implemented previously is too simplistic, because it just checks if there's an even or odd number of quotes in the …
> fix: apostrophes in tags

- README.md
- src/django_components/component.py
- src/django_components/slots.py
- src/docs/concepts/fundamentals/slots.md
- tests/test_templatetags_provide.py
Small bug I came across when there is a component nested in another component, whereas the inner one uses `inject()` to use data provided by the outer component.
E.g.
```django
{% component "data_provider" %}
{%  component "data_user" / %}
{% endcomponent %}
```
This errored, because we tried to render `data_user` component as part of searching for `{% fill %}` tags. But at that point the `data_provider` has not yet provided the data.
So the solution is NOT to render the `{% component %}` tags at that stage.
> fix: do NOT render component tags when parsing {% component %} body for fills

- src/django_components/component.py
- src/django_components/slots.py
- tests/test_templatetags_slot_fill.py
Another bug I encountered while trying to update to v0.110.
When I had a following template:
```django
{% if component_vars.is_filled.activator %}
<div>
{% slot "activator" default / %}
</div>
{% endif %}
```
And I used the component WITHOUT the implicit / default fill:
```django
{% component "Menu" /  %}
```
Then I was getting error
```
Component 'Menu' passed default fill content (i.e. without explicit 'name' kwarg), even though none of its slots is marked as 'default'.
```
While this error made sense when slots were defined statically, it doesn't make sense anymore. Because as you can see above in the template, the default slot still IS defined in the template. But it's just that it was not rendered, because the `{% if %}` branch didn't run.
So I removed the error.
> fix: allow components to accept default fill even if no default slot was encountered during rendering

- src/django_components/dependencies.py
- tests/test_dependency_rendering.py
One more bug fix as I was trying to update my project to v0.110. Turns out that Python's Set does NOT preserve order, which was causing JS and CSS defined via `Component.Media.js/css` to change positions.
> fix: ensure consistent order of scripts in Component.Media.js

- CHANGELOG.md
- src/django_components/component.py
- src/django_components/slots.py
- tests/test_component.py
- tests/test_templatetags_component.py
- tests/test_templatetags_provide.py
One more bug found. This bug is practically the same as the one in https://github.com/EmilStenstrom/django-components/pull/778/files, where I had to add following snippet to `ComponentNode`:
```py
if _is_extracting_fill(context):
return ""
```
Except this time this snippet is needed for `SlotNode`.
Beside that, I also updated the error message when an error occurs while rendering a component. Now it shows the component path like so:
```
KeyError: "An error occured while rendering components ProjectPage > ProjectLayoutTabbed >
Layout > RenderContextProvider > Base > TabItem:
Component 'TabItem' tried to inject a variable '_tab' before it was provided."
```
> fix: do not render slot tag when extracting fill tags

- src/docs/README.md
I wasn't aware of this, but when with mkdocs, the `README.md` at the root of the docs directory will be converted to top-level `index.html` file.
Currently, you can see that the updated docs have been published under the `dev` tag:
https://emilstenstrom.github.io/django-components/dev/overview/welcome/
But when you try to go to the docs via the version dropdown, it redirects you to the root:
https://emilstenstrom.github.io/django-components/dev/
Which returns 404, because it's missing the `index.html` file.
So this MR adds the missing file.
> refactor: re-add top-level docs/README.md to re-add missing index.html

- mkdocs.yml
This PR address [this comment](https://github.com/EmilStenstrom/django-components/pull/803#pullrequestreview-2479761726) about the homepage and "/overview/welcome" pages looking slightly different.
So this configures the docs redirects so that when user goes to root page, they get redirected to "/overview/welcome"
> refactor: configure top-level redirect for docs

- pyproject.toml
- requirements-dev.in
- requirements-dev.txt
- requirements-docs.txt
- src/django_components/dependencies.py
- src/django_components/util/html.py
- src/django_components/util/misc.py
- tests/test_dependencies.py
- tests/test_html.py
This supersedes the PR https://github.com/EmilStenstrom/django-components/pull/797.
In short, this replaces [Selectolax](https://github.com/rushter/selectolax) library with [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/).
My cup hath runneth over with Selectolax / Lexbor for 3 reasons:
1. It modifies the HTML, e.g. inserting the extra `<html>`, `<head>`, `<body> tags.
2. It tries to fix / modify the HTML, e.g. adding a closing tag when it comes across an unclosed one.
3. I cannot access body of `<template>` tags (see https://github.com/rushter/selectolax/issues/146).
Reasons 1 and 2 are annoying, but 3) is flat-out a deal-breaker.
---
Initially I tried to replaces Selectolax with [lxml](https://lxml.de/), because lxml is also compiled to C and has similar performance as …
> refactor: replace selectolax with beautifulsoup

- src/django_components/util/tag_parser.py
- tests/test_tag_parser.py
Fix a bug in tag parser where if a value was a translation, e.g.
`{% component _("my_text") %}`
then the `_()` were being accidentally stripped.
Closes https://github.com/EmilStenstrom/django-components/issues/847
> fix: format tag param with translation correctly

- README.md
As we've now removed the docs from the README, I think we should make a little more effort to send people to the docs. Here's a trick to do that in markdown, using a header and a table.
> Make link to docs more prominent

- CHANGELOG.md
- docs/concepts/fundamentals/defining_js_css_html_files.md
- docs/css/style.css
- src/django_components/__init__.py
- src/django_components/component.py
- src/django_components/component_media.py
Adds missing documentation for https://github.com/EmilStenstrom/django-components/pull/870
> docs: add documentation around component media

- CHANGELOG.md
- README.md
- docs/concepts/advanced/component_registry.md
- docs/concepts/fundamentals/defining_js_css_html_files.md
- docs/concepts/fundamentals/single_file_components.md
- docs/concepts/getting_started/adding_js_and_css.md
- docs/concepts/getting_started/adding_slots.md
- docs/concepts/getting_started/components_in_templates.md
- docs/concepts/getting_started/parametrising_components.md
- docs/concepts/getting_started/your_first_component.md
- docs/guides/devguides/slots_and_blocks.md
- docs/overview/welcome.md
- sampleproject/components/calendar/calendar.py
- sampleproject/components/nested/calendar/calendar.py
- sampleproject/components/todo/todo.py
- src/django_components/component.py
- src/django_components/component_media.py
- src/django_components/management/commands/startcomponent.py
- tests/components/multi_file/multi_file.py
- tests/components/relative_file/relative_file.py
- tests/components/relative_file_pathobj/relative_file_pathobj.py
- tests/components/staticfiles/staticfiles.py
- tests/test_app/components/app_lvl_comp/app_lvl_comp.py
- tests/test_app/custom_comps_dir/app_lvl_comp/app_lvl_comp.py
- tests/test_component.py
- tests/test_component_media.py
- tests/test_templatetags.py
- tests/test_templatetags_component.py
- tests/test_templatetags_extends.py
Follow up from https://github.com/EmilStenstrom/django-components/pull/870#issuecomment-2565828739
Changes:
- Renamed `Component.template_name` to `Component.template_file`
- Some linting changes here and there, triggered by search-and-replace
- Added new `template_name` which forward all access and setting to `template_file` via descriptors (see https://github.com/EmilStenstrom/django-components/pull/878/commits/7cb60c89bd0b5a42913c29279ac3ee8a5af41c9c)
> refactor: rename template_name to template_file

- src/django_components/dependencies.py
- src/django_components/util/html.py
- tests/test_context.py
- tests/test_dependencies.py
- tests/test_expression.py
This updates BS4 to use the HTML5 parser, as mentioned in [this discussion](https://github.com/EmilStenstrom/django-components/pull/870#issuecomment-2565712822).
Turns out that there was far fewer tests to fix after the change.
> refactor: use HTML5 parser for BeautifulSoup

- src/django_components/templatetags/component_tags.py
- src/django_components/util/tag_parser.py
- tests/test_expression.py
- tests/test_tag_parser.py
Following up on https://github.com/EmilStenstrom/django-components/issues/872, because, frankly, it was fun to solve 😄 
This PR refactors the tag parser, which turns Django's template tag content of e.g.
`{% component key=value key2="abc def" / %}`
into an AST which can be worked with downstream.
1. This PR fixes the bug in https://github.com/EmilStenstrom/django-components/issues/894 - after this PR, it will be possible to have whitespace around filters and translation syntax:
`{% component key=_(   "hello"  ) key2="abc def"   |   lower / %}`
2. I added support for defining list and dict literals as inputs, and allowing to spread variables into those literal lists and dicts.
I then took this idea to its logical conclusion, allowing nested lists, dicts, etc. So the syntax works as …
> feat: list and dict literals in tags + fix tag parser

- docs/scripts/reference.py
- src/django_components/templatetags/component_tags.py
- src/django_components/util/template_tag.py
- tests/test_template_parser.py
Bit of cleanup before I do next part of https://github.com/EmilStenstrom/django-components/issues/872. 
I moved the helper functions from the file where the template tags are defined to its own file in the `util` folder. No logic change.
> refactor: move the utils from component_tags to util.template_tag

- src/django_components/component.py
- src/django_components/dependencies.py
- src/django_components/util/misc.py
To illustrate a possible fix of #930
EDIT:
I think this is decent by now.
I'm not sure how I could write a test for this, at least not in a way which would provoke the error from the issue above without a disproportionate amount of work, but all tests pass and many of them rely on this logic working.
> fix: implement safe retrieval of component classes from registry

- sampleproject/components/recursive.py
- sampleproject/components/urls.py
- src/django_components/component.py
- src/django_components/components/dynamic.py
- src/django_components/context.py
- src/django_components/dependencies.py
- src/django_components/node.py
- src/django_components/perfutil/component.py
- src/django_components/perfutil/provide.py
- src/django_components/provide.py
- src/django_components/slots.py
- src/django_components/util/context.py
- src/django_components/util/exception.py
- src/django_components/util/logger.py
- src/django_components/util/misc.py
- tests/test_component.py
- tests/test_context.py
- tests/test_dependencies.py
- tests/test_expression.py
- tests/test_template.py
- tests/test_templatetags_component.py
- tests/test_templatetags_extends.py
- tests/test_templatetags_provide.py
- tests/test_templatetags_slot_fill.py
- tests/test_templatetags_templating.py
Closes #923 
The main goal of this PR was to work around the recusion limits when rendering deeply-nested (see https://github.com/django-components/django-components/issues/923).
I achieved this by:
1. If component is nested in another, instead of the inner component directly rendering its contents, it returns only a placeholder. After the root component is rendered, we check the HTML for any component placeholders, and replace them. It's at this point when we actually render the child components. This repeats recursively - if child component has subcomponents, those subcomponnt will first return only a placeholder, and will be rendered in next iteration. Thus, parent components get to be rendered before child components.
2. To avoid needing to use recursion, when a component's template …
> refactor: fix component recursion

- src/django_components/node.py
- src/django_components/util/template_tag.py
- tests/test_attributes.py
- tests/test_expression.py
- tests/test_node.py
Part of #935.
As described [here](https://github.com/django-components/django-components/issues/935#issuecomment-2629165443), I tried to replace `eval()` with manual input validation, to see if it improves performance.
I does not. But at least we got rid of the eval, so that's still a win in my book.
No API changes.
> refactor: remove use of eval for node validation

- src/django_components/node.py
- src/django_components/util/template_tag.py
- tests/test_node.py
Part of https://github.com/django-components/django-components/issues/935
This adds an alternative implementation of validating tag inputs, which relies on the `__code__` internals to get the function's  signature (see https://github.com/django-components/django-components/issues/935#issuecomment-2629317588).
This alternative is about 3x faster (46ms vs 16ms on my test page of 2 MB HTML and 360 components). If `__code__` is NOT available, we still fall back to the signature-based implementation, so that django-components can still be potentially used also on more exotic Python flavours.
> refactor: Do tag input validation with __code__ variables if available

- CHANGELOG.md
- docs/guides/setup/caching.md
- docs/guides/setup/development_server.md
- docs/guides/setup/syntax_highlight.md
- docs/overview/installation.md
- docs/reference/settings.md
- docs/reference/template_tags.md
- src/django_components/app_settings.py
- src/django_components/cache.py
- src/django_components/component.py
- src/django_components/dependencies.py
- src/django_components/template.py
- tests/test_cache.py
- tests/testutils.py
Changes:
- Use Django's Loc mem cache instead of custom implementation for storing JS / CSS scripts
- Added `COMPONENTS.cache` setting
- Updated installation
- Added docs article on caching
Closes https://github.com/django-components/django-components/issues/940
> feat: allow to configure media cache (for JS and CSS files)

- src/django_components/component.py
- tests/templates/relative_extends.html
- tests/test_templatetags_extends.py
Hi, i've created some test to demonstrate an issue i'm facing when : 
- Component use `template_file` to declare it's template
- template use `extends` or `include` with relative path e.g: `../base_template.html`
> Bug : Relative path in `extends` and `include` does not work when using template_file

- CHANGELOG.md
- src/django_components/util/cache.py
- tests/test_cache.py
Closes https://github.com/django-components/django-components/issues/974
> refactor: fix error when template cache is set to 0

- pyproject.toml
Docs publish and release pipeline [failed](https://github.com/django-components/django-components/actions/runs/13433593422/job/37530728162) because I forgot to add the dependencies to pyproject.toml.
This should fix it
> refactor: fix missing docs dependencies

- docs/getting_started/.nav.yml
- docs/getting_started/rendering_components.md
Add a section to "Getting Started" to describe how to render components.
Closes #990
https://github.com/user-attachments/assets/e532afe1-28b4-4062-85d2-8d88782cf792
> docs: document how to render components in getting started

- .github/workflows/pr-benchmark-comment.yml
- .github/workflows/pr-benchmark-generate.yml
The workflow for benchmarking the PR and posting the results consists of two Github actions:
1. Check out to PR, install deps, run the benchmarks, save them as files ([workflow artifacts](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/storing-and-sharing-data-from-a-workflow))
2. Load the saved file, and post it to the PR as a comment.
The second part is currently not working, because the second workflow is unable to get the metadata about which PR to write the comment to.
Don't know why that metadata is missing, there were some cases where it worked, and I wasn't able to figure out why it's not available.
So in this PR I'm trying a different approach to pass the PR number:
- Before, I tried accessing the metadata from within the second workflow with …
> refactor: save PR number to a file to access it when posting a benchmark comment

- CHANGELOG.md
- docs/concepts/advanced/component_registry.md
- docs/concepts/advanced/extensions.md
- docs/reference/api.md
- src/django_components/__init__.py
- src/django_components/component.py
- src/django_components/component_media.py
- src/django_components/component_registry.py
- src/django_components/extension.py
- src/django_components/slots.py
- src/django_components/util/testing.py
- tests/test_component.py
- tests/test_extension.py
- tests/test_registry.py
PR with various small changes related to writing extensions, as mentioned here https://github.com/django-components/django-components/pull/1025#issuecomment-2727405187
- Add `ComponentRegistry.has()` to check if a component is registered without raising an error.
- Get all created `Component` classes with `all_components()`.
- Get all created `ComponentRegistry` instances with `all_registries()`.
> feat: registry.has(); helpers to get all components and registries; access component from ext class

- README.md
- docs/concepts/advanced/extensions.md
- docs/reference/commands.md
- pyproject.toml
- src/django_components/commands/components.py
- src/django_components/commands/ext_list.py
- src/django_components/commands/ext_run.py
- src/django_components/commands/list.py
- src/django_components/util/misc.py
- tests/test_command_ext.py
- tests/test_command_list.py
Add the `components list` command that lists all components like so:
```txt
full_name                                                     path
==================================================================================================
project.pages.project.ProjectPage                             project/pages/project
project.components.dashboard.ProjectDashboard                 project/components/dashboard
project.components.dashboard_action.ProjectDashboardAction    project/components/dashboard_action
```
Also the `components ext list` command was updated to use the same underlying logic as this new list command.
I thought I'd get this one in before releasing the extensions feature.
Closes https://github.com/django-components/django-components/issues/1024
> feat: add a command to list all components

- .github/workflows/docs.yml
Fix (hopefully) for https://github.com/django-components/django-components/issues/1044.
The issue is that `master` is a protected branch, and the CI bot doesn't have permissions to push to that branch.
One potential workaround is to use the `gh` CLI tool to create a PR with the changes, and also push it, before updating the docs.
> ci: Make a separate PR when pushing release benchmark data

- .github/workflows/pr-benchmark-generate.yml
[This workflow](https://github.com/django-components/django-components/actions/runs/13979989243/job/39160267799?pr=1043) failed, and I can't see why because there's no output to the terminal from the command that does the comparison (`asv compare`)*.
So this PR makes the comparison command run twice - once with `--verbose` flag, which will be printed out to the terminal, and once without, which will print out the actual results and save them as before.
\* Note: the `No module named 'libmambapy'` in the workflow output is a red herring
> refactor: display verbose output for benchmark comparison

- .github/dependabot.yml
- .github/workflows/publish-to-pypi.yml
- CHANGELOG.md
- docs/overview/compatibility.md
- pyproject.toml
- requirements-dev.txt
- requirements-docs.txt
- tox.ini
In https://github.com/django-components/djc-core-html-parser/pull/3 I've updated the parser package to be built also for Python 3.13, and released that as [v1.0.2](https://github.com/django-components/djc-core-html-parser/releases/tag/1.0.2).
The 1.0.2 release now contains also Windows + Python 3.13 build:
Next, in this django-components package, I've pinned the `djc-core-html-parser` package, to ensure it uses the version with fixed builds.
Other than that, I also included other suggestions from https://github.com/django-components/django-components/issues/1053:
- Document that we use this Rust-based subpackage underneath + implications
- Update our Github Actions
- Update Dependabot to also update Github actions automatically
Closes …
> build: add support for py3.13 windows

- CHANGELOG.md
- pyproject.toml
- src/django_components/component_media.py
- tests/components/glob/glob.py
- tests/test_component_media.py
Further fix for https://github.com/django-components/django-components/issues/1062, as raised in https://github.com/django-components/django-components/pull/1065.
@DNIIBOY Could you test this PR locally to see if it works for your case? IMO it should work, but better to double check.
And sorry for making yet another PR, I don't want to modify other people's PRs (unless it's tiny things) to avoid confusion.
Supersedes https://github.com/django-components/django-components/pull/1065.
> refactor: fix component media URLs

- CHANGELOG.md
- benchmarks/benchmark_templating.py
- docs/concepts/fundamentals/.nav.yml
- docs/concepts/fundamentals/component_defaults.md
- docs/getting_started/parametrising_components.md
- docs/reference/api.md
- docs/reference/template_tags.md
- src/django_components/__init__.py
- src/django_components/app_settings.py
- src/django_components/component.py
- src/django_components/extensions/defaults.py
- src/django_components/util/tag_parser.py
- tests/test_command_ext.py
- tests/test_component.py
- tests/test_component_defaults.py
- tests/test_extension.py
This PR adds the option to set defaults on Components, as described in https://github.com/django-components/django-
components/issues/881
Closes https://github.com/django-components/django-components/issues/881
Sreenshots:
> feat: allow to set defaults

- CHANGELOG.md
- docs/concepts/advanced/typing_and_validation.md
- src/django_components/app_settings.py
- src/django_components/extension.py
- tests/test_finders.py
Small fixes to be part of v0.136:
- Renamed the module import path of djc-ext-pydantic from `djc_ext_pydantic` to `djc_pydantic`
- Trigger `URLResolver._populate()` when we are registering extensions to allow the URLs introduced by extensions to be looked up with `reverse()`
> refactor: fix ext URLs lookup

- CHANGELOG.md
- docs/guides/devguides/dependency_mgmt.md
- docs/reference/api.md
- docs/reference/urls.md
- docs/scripts/reference.py
- src/django_components/__init__.py
- src/django_components/component.py
- src/django_components/component_registry.py
- src/django_components/dependencies.py
- src/django_components/extensions/url.py
- tests/test_cache.py
- tests/test_component.py
- tests/test_component_url.py
For the Storybook integration, I needed to uniquely identify components from the Storybook UI. So I wanted to reuse the `_class_hash` that's already available. But `_class_hash` was an internal variable. So this PR exposes it publicly as `Component.class_id`.
Together with this goes accessing the component classes based on their new class IDs. So I've also added `get_component_by_class_id()` for that. It's a bit mouthful, but since components also have the instance IDs under `Component.id`, I went with unambiguous name.
```py
from django_components import Component, get_component_by_class_id
class MyComp(Component):
pass
assert MyComp is get_component_by_class_id(MyComp.class_id)
```
> feat: expose _class_hash as class_id

- README.md
- docs/overview/welcome.md
Tiny docs update to mention the URL endpoint auto generation in the README in the HTML fragment section. What prompted me was that there was a positive feedback from one guy on Reddit on this feature, but I realized that it's not mentioned in the overview.
> docs: mention URL auto-gen in README

- CHANGELOG.md
- pyproject.toml
- src/django_components/finders.py
- tests/test_finders.py
In Django 5.2 the `Finder.find()` attribute receives a `find_all` kwarg instead of `all` kwarg ([see changelog](https://docs.djangoproject.com/en/5.2/releases/5.2/#features-deprecated-in-5-2)). So, depending on the Django version, our `ComponentsFileSystemFinder` will use either one or another.
Closes https://github.com/django-components/django-components/issues/1119
> refactor: fix compat with Django 5.2 Finder.find()

- CHANGELOG.md
- README.md
- docs/concepts/advanced/authoring_component_libraries.md
- docs/concepts/advanced/extensions.md
- docs/concepts/advanced/typing_and_validation.md
- docs/concepts/fundamentals/components_in_python.md
- docs/overview/welcome.md
- docs/reference/api.md
- docs/reference/commands.md
- docs/reference/extension_hooks.md
- docs/reference/template_tags.md
- pyproject.toml
- requirements-ci.in
- requirements-ci.txt
- requirements-dev.in
- requirements-dev.txt
- src/django_components/component.py
- src/django_components/extension.py
- src/django_components/template.py
- tests/test_component.py
- tests/test_extension.py
When typing a Component, one can now specify as few or as many parameters as you want.
```py
Component[Args]
Component[Args, Kwargs]
Component[Args, Kwargs, Slots]
Component[Args, Kwargs, Slots, Data]
Component[Args, Kwargs, Slots, Data, JsData]
Component[Args, Kwargs, Slots, Data, JsData, CssData]
```
All omitted parameters will default to `Any`.
Closes #1113
> refactor: use typevar defaults + raise on conflicting extensions

- .github/workflows/tests.yml
When running CI tests for https://github.com/django-components/django-components/issues/1136#issuecomment-2816850699, there was a notification from Github that their Ubuntu 20.04 image was deprecated.
So I've updated the jobs to run on the latest Ubuntu
> ci: update ubuntu version

- CHANGELOG.md
- docs/concepts/advanced/html_fragments.md
- docs/concepts/advanced/rendering_js_css.md
- docs/concepts/fundamentals/html_js_css_files.md
- docs/concepts/fundamentals/rendering_components.md
- docs/reference/api.md
- docs/reference/template_tags.md
- requirements-docs.txt
- sampleproject/components/calendar/calendar.py
- sampleproject/components/fragment.py
- sampleproject/components/nested/calendar/calendar.py
- src/django_components/__init__.py
- src/django_components/component.py
- src/django_components/components/dynamic.py
- src/django_components/dependencies.py
- tests/e2e/testserver/testserver/views.py
- tests/test_dependencies.py
Closes https://github.com/django-components/django-components/issues/971
The actual convo is here https://github.com/django-components/django-components/pull/959#issuecomment-2824018780
---
Currently in django-components we assumed that components would be rendered only in browsers. So even if one wanted to use djc to generate HTML for emails, we would still insert the `<script>` tag with our client-side dependency manager.
There were two "modes" for deciding how to render the JS and CSS, configured by the `type` kwarg that we pass to `Component.render()` - `"document"` and `"fragment"`.
This PR adds 3 more options - `"simple"`, `"prepend"`, `"append"`
```py
Calendar.render_to_response(
request=request,
kwargs={
"date": request.GET.get("date", ""),
},
type="append",
)
```
Overview
- …
> feat: add "simple", "prepend", and "append" render types

- CHANGELOG.md
- docs/concepts/fundamentals/component_views_urls.md
- src/django_components/extensions/view.py
- src/django_components/util/misc.py
- tests/test_component.py
- tests/test_component_view.py
Updates `get_component_url()` to now optionally accept `query` and `fragment` arguments.
```py
from django_components import get_component_url
url = get_component_url(
MyComponent,
query={"foo": "bar"},
fragment="baz",
)
```
Closes https://github.com/django-components/django-components/issues/1149
> feat: allow to set query and fragment on get_component_url

- CHANGELOG.md
- docs/reference/extension_hooks.md
- docs/reference/template_tags.md
- docs/scripts/reference.py
- src/django_components/component.py
- src/django_components/extension.py
- tests/test_extension.py
Made this a separate PR from https://github.com/django-components/django-components/pull/1161 so that https://github.com/django-components/django-components/pull/1161 contained no new changes / suggestions.
As part of renaming `get_context_data` to `get_template_data`, there is also one object that had field `context_data`. This PR renames it to `template_data`.
The object was available from within the `on_component_data` extension hook.
Again the old field is kept for backwards compatibility and tagged to be removed in v1.
> refactor: rename `context_data` field to `template_data`

- CHANGELOG.md
- src/django_components/util/context.py
- tests/test_context.py
See #1165 
When generating context processors data, in `gen_context_processors_data()`, we meant to cache the results, so we would reuse the same data for the same request object. But the line of code to save the generated data was missing.
Closes #1165
> Fix context processors

- CHANGELOG.md
- docs/reference/commands.md
- docs/reference/template_tags.md
- src/django_components/extension.py
- src/django_components/extensions/cache.py
- src/django_components/extensions/view.py
- src/django_components/util/command.py
- src/django_components/util/routing.py
- tests/test_component_cache.py
Phew, last one for today!
As mentioned in https://github.com/django-components/django-components/issues/1164#issuecomment-2849451094, this is part of changes to allow component caching to take into the account the slots that were used to render the component.
This specific PR only updates the methods of `Component.Cache` so they already receive the slots. This is so that this small breaking change is released with the rest of them in v0.140.
Before:
```py
def get_cache_key(self, *args: Any, **kwargs: Any) -> str:
def hash(self, *args: Any, **kwargs: Any) -> str:
```
After:
```py
def get_cache_key(self, args: Any, kwargs: Any, slots: Any) -> str:
def hash(self, args: Any, kwargs: Any) -> str:
```
> refactor: Change caching methods to accept slots + typing fixes

- CHANGELOG.md
- docs/concepts/advanced/template_tags.md
- src/django_components/component.py
- src/django_components/node.py
- src/django_components/util/template_tag.py
- tests/test_node.py
Another part towards https://github.com/django-components/django-components/issues/1164.
This modifies our implementation of template tags so that the Node (well, `BaseNode`) class remembers what was the content of the body (the string between `{% tag %}` / `{% endtag %}`), and makes it accessible via `BaseNode.contents`.
> feat: add BaseNode.contents

- CHANGELOG.md
- src/django_components/component.py
- src/django_components/slots.py
- tests/test_component.py
- tests/test_slots.py
- tests/test_templatetags_slot_fill.py
Part of https://github.com/django-components/django-components/issues/1164
This updates the `Slot` class and its constructor such that it exposes `Slot.contents`, which contains the original contents:
- If `Slot` was created from `{% fill %}` tag, `Slot.contents` will contain the body (string) of the `{% fill %}` tag.
- If `Slot` was created from string via `Slot("...")`, `Slot.contents` will contain that string.
- If `Slot` was created from a function, `Slot.contents` will contain that function.
- If `Slot` was created from another Slot `Slot(slot)`, `Slot.contents` will contain the inner slot's `Slot.contents`.
> feat: Expose slot input as Slot.contents

- CHANGELOG.md
- src/django_components/__init__.py
- src/django_components/component.py
- src/django_components/slots.py
- tests/test_slots.py
- tests/test_templatetags_slot_fill.py
- tests/test_templatetags_templating.py
Renamed to avoid confusion between `{% slot default %}` and `{% fill default="..." %}`
The old kwarg `{% fill default="..." %}` is still avaialble with the plan to remove it in v1.
I didn't update the documentation page in ["concepts/fundamentals/slots"](https://django-components.github.io/django-components/0.139.1/concepts/fundamentals/slots/) in this PR, because there's could more PRs after this one, so then there is one PR that solely just updates the docs page.
> refactor: Rename `{% fill default=... %}` to `{% fill fallback=... %}`

- CHANGELOG.md
- docs/concepts/advanced/component_caching.md
- src/django_components/extensions/cache.py
- tests/test_component_cache.py
This makes component caching consider also the given slots.
The slot caching is not perfect - it doesn't consider when context variables in the template change. As such, it's opt-in with `include_slots=True`.
```python
class MyComponent(Component):
class Cache:
enabled = True
include_slots = True
```
Closes #1164
> feat: slot caching

- CHANGELOG.md
- docs/concepts/advanced/component_caching.md
- docs/concepts/fundamentals/rendering_components.md
- docs/concepts/fundamentals/typing_and_validation.md
- src/django_components/__init__.py
- src/django_components/component.py
- src/django_components/slots.py
- tests/test_component.py
- tests/test_component_cache.py
- tests/test_component_typing.py
- tests/test_slots.py
- tests/test_templatetags_slot_fill.py
Breaking change to simplify the slot functions API:
- Defining slot functions:
Before:
```py
def slot_fn(context: Context, data: Dict, slot_ref: SlotRef):
isinstance(context, Context)
isinstance(data, Dict)
isinstance(slot_ref, SlotRef)
return "CONTENT"
```
After:
```py
def slot_fn(ctx: SlotContext):
assert isinstance(ctx.context, Context) # May be None
assert isinstance(ctx.data, Dict)
assert isinstance(ctx.fallback, SlotFallback) # May be None
return "CONTENT"
```
- Calling slot functions:
Before:
```py
def slot_fn(context: Context, data: Dict, slot_ref: SlotRef):
return "CONTENT"
html = slot_fn(Context(), None, None)  # All inputs were required and all positional
html = slot(Context(), {"data1": "abc", "data2": "hello"}, None)
html = slot(Context(), {"data1": "abc", "data2": "hello"}, …
```
> refactor: simplify slot API

- CHANGELOG.md
- src/django_components/slots.py
- tests/test_slots.py
This PR allows to pass `Slot` instances to `{% fill %}` tags. Basically a mechanism to render the Python-defined Slots in the template.
Closes https://github.com/django-components/django-components/issues/1171
In the discussion there were options for the kwarg name like `slot`, `contents`, or `with`.
- `slot` was confusing, and could not use `with`, because it's a Python keyword. And `contents` feels too long.
- So I set the kwarg name to `body`, as in "set the body of this fill tag"
So the final API looks like this:
```python
from django_components import component, Slot
class Table(Component):
def get_template_data(self, args, kwargs, slots, context):
return {
"my_slot": Slot(lambda ctx: "Hello, world!"),
}
```
Then pass the slot to the `{% fill %}` tag:
```django
{% component "table" …
```
> feat: Pass Slots to {% fill %} with 'body' kwarg

- README.md
- docs/concepts/fundamentals/.nav.yml
- docs/concepts/fundamentals/slots.md
- docs/getting_started/adding_slots.md
- docs/getting_started/components_in_templates.md
Documents the recent changes to slots.
Here's preview of it. I've moved the video to Youtube, because Github has file limit 10mb, and the last time I tried to compress similar video, it ended up choppy as hell 😄 
https://youtu.be/x6yCEwt0rUk
- All the ways how to use slots / fills is now documented in consice overview.
- Added section on the Slot class
- `{{ component_vars.is_filled }}` was moved to the bottom as legacy section.
Closes https://github.com/django-components/django-components/issues/1095
> docs: update docs on slots

- CHANGELOG.md
- docs/concepts/fundamentals/slots.md
- docs/reference/api.md
- docs/reference/commands.md
- docs/reference/extension_hooks.md
- docs/reference/signals.md
- docs/reference/template_tags.md
- docs/reference/template_vars.md
- src/django_components/component.py
- src/django_components/extension.py
- src/django_components/extensions/defaults.py
- src/django_components/provide.py
- src/django_components/slots.py
- tests/test_slots.py
This PR makes is so that passing `Slot` instance to `Slot()` constructor raises an error. Other than that, it's then more documentation and a bit of moving stuff around.
> refecator: move defaults applying back to ext, raise on passing Slot to Slot, and docs cleanup

- CHANGELOG.md
- docs/concepts/advanced/template_tags.md
- docs/reference/commands.md
- docs/reference/template_tags.md
- sampleproject/sampleproject/settings.py
- src/django_components/app_settings.py
- src/django_components/cache.py
- src/django_components/commands/upgrade.py
- src/django_components/component.py
- src/django_components/component_media.py
- src/django_components/node.py
- src/django_components/slots.py
- src/django_components/template.py
- src/django_components/template_loader.py
- src/django_components/util/django_monkeypatch.py
- src/django_components/util/testing.py
- tests/test_benchmark_django.py
- tests/test_benchmark_django_small.py
- tests/test_benchmark_djc.py
- tests/test_benchmark_djc_small.py
- tests/test_component.py
- tests/test_component_media.py
- tests/test_context.py
- tests/test_node.py
- tests/test_signals.py
- tests/test_template.py
- tests/test_templatetags.py
- tests/test_templatetags_component.py
- tests/test_templatetags_extends.py
- tests/testutils.py
Sorry for big PR, I already removed one part of it, but what remains is all too closely related.
Changes:
Changes that relate to how the component templates are loaded / created:
- `Component.template` no longer accepts a Template instance*, only plain string.
- `Component.get_template_name()` and `Component.get_template()` are now deprecated. 
In other words, the Template should now be specified as plain string (`Component.template`) or file (`Component.template_file`).
With these changes, we will have control over how the template string is compiled into `Template` instance, and will allow us (or our extensions) to pre-process the template. Thus we can implement Vue-like or django-cotton-like syntax as an extension.
As a side effect, we can also deprecate `template_cache_size` setting …
> refactor: deprecate template caching, get_template_name, get_template, assoc template with Comp cls

- CHANGELOG.md
- docs/concepts/advanced/template_tags.md
- docs/concepts/fundamentals/render_api.md
- docs/concepts/fundamentals/slots.md
- docs/reference/api.md
- docs/reference/extension_hooks.md
- docs/reference/template_tags.md
- src/django_components/__init__.py
- src/django_components/component.py
- src/django_components/extension.py
- src/django_components/node.py
- src/django_components/provide.py
- src/django_components/slots.py
- tests/test_component.py
- tests/test_extension.py
- tests/test_node.py
- tests/test_slots.py
Ok, this is the last PR related to slots and after this I'm [done working on slots](https://github.com/django-components/django-components/issues/433#issuecomment-2826726311) until v1 🤞 
This PR wires up metadata, so we can trace back to their origin when we have a Component or a Slot instance:
- If component comes from `{% component %}` tag, then `Component.node` will point to the `ComponentNode`
- If a slot fill comes from `{% fill %}` tag, then `Slot.fill_node` points to `FillNode`
- If a slot fill comes from `{% component %}` tag (AKA default fill), then `Slot.fill_node` points to that `ComponentNode`.
In extensions:
- In `on_slot_rendered` hook, one can access the original `{% slot %}` tag (aka `SlotNode`) via `ctx.slot_node`.
Moreover each template tag node defined by us (with our …
> refactor: Add Node metadata

- CHANGELOG.md
- README.md
- docs/concepts/fundamentals/component_defaults.md
- docs/concepts/fundamentals/html_js_css_variables.md
- docs/concepts/fundamentals/render_api.md
- docs/overview/welcome.md
- docs/reference/template_tags.md
- src/django_components/component.py
- src/django_components/components/dynamic.py
- src/django_components/slots.py
- tests/test_benchmark_djc.py
- tests/test_component.py
- tests/test_component_defaults.py
- tests/test_slots.py
- tests/test_templatetags_slot_fill.py
Last one before v0.140 🎉 🎉 @EmilStenstrom thank you for your infinite patience! 😄 
As mentioned in #1206, this marks `Component.input` as deprecated.
In order to avoid using `Component.input`, following Component attributes were added:
- `Component.raw_args` - Same as `input.args` - Positional args. Unlike `Component.args` this stays as plain list even when `Component.Args` is given.
- `Component.raw_kwargs` - Same as above, but for `kwargs`
- `Component.raw_slots` - Same as above, but for `slots`
- `Component.deps_strategy` - Stores the value passed to `Component.render()`, because it was stored only on `input.deps_strategy`.
Closes #1206
> refactor: deprecate Component.input and add raw_args, raw_kwargs, raw_slots

- src/django_components/slots.py
Turns out there's a code branch that's not tested in unit tests, but that's hit with benchmarks.
This PR fixes the typo that was there.
See https://github.com/django-components/django-components/actions/runs/15453716971/job/43501607141
> fix: ctx_with_fills.fill

- docs/getting_started/parametrising_components.md
The phrase indicating the "next step" seemed to be in the wrong position.
I have moved it so that it appears at the end.
> docs: fix parametrising components section next step line position

- docs/getting_started/rendering_components.md
Sections 4 and 5 were missing numbers on the "Rendering components" page.
For consistency, section numbers have been added.
> docs: add section numbering to Rendering components page

- docs/reference/.nav.yml
Issue - https://github.com/django-components/django-components/issues/1294
Reflected the filename change from commit 458e189 in the nav, which was previously not updated.
> docs: fix wrong link to template variable page in sidebar

- .github/workflows/docs.yml
Follow up to https://github.com/django-components/django-components/pull/1347 because the [CI failed](https://github.com/django-components/django-components/actions/runs/17712428350/job/50332888550) when building the docs.
> refactor: call mike as bin, not module

- .github/workflows/docs.yml
Another follow up to https://github.com/django-components/django-components/pull/1347 and https://github.com/django-components/django-components/pull/1376
> ci: add missing django-components during docs build

- CHANGELOG.md
- docs/reference/commands.md
- docs/reference/components.md
- docs/reference/template_tags.md
- src/django_components/__init__.py
- src/django_components/apps.py
- src/django_components/components/__init__.py
- src/django_components/components/error_fallback.py
- tests/test_component_error_fallback.py
- tests/test_loader.py
Add ErrorFallback (originally mentioned in https://github.com/django-components/django-components/issues/1085) built-in component. Available from within the template under `error_fallback`.
This works similarly to React's ErrorBoundary - It wraps the rest of the template. If the thing that's inside throws error, ErrorFallback captures that, and renders the fallback content instead.
Either pass the fallback as a kwarg:
```django
{% component "error_fallback" fallback="Oops, something went wrong" %}
{% component "table" / %}
{% endcomponent %}
```
Or use the full `fallback` slot:
```django
{% component "error_fallback" %}
{% fill "content" %}
{% component "table" / %}
{% endfill %}
{% fill "fallback" data="data" %}
<p>Oops, something went wrong</p>
{% button href="/report-error" %}
Report …
```
> feat: add ErrorFallback

- CHANGELOG.md
- pyproject.toml
- src/django_components/apps.py
- src/django_components/components/error_fallback.py
- src/django_components/util/django_monkeypatch.py
- tests/test_dependency_rendering.py
Fix for https://github.com/django-components/django-components/pull/1390
Also fixes another bug that was introduced in v0.142.0 where I forgot to add `{% load component_tags %}` inside the `ErrorFeedback`'s template.
> refactor: fix djc not working when not among built-ins
