django-components/django-components

django_components/__init__.py
django_components/app_settings.py
django_components/apps.py

Tests pass but this should probably be tested manually in an example app.

Autodiscover

---

django_components/component.py
django_components/templatetags/component_tags.py
tests/templates/template_with_illegal_slot.html
tests/test_templatetags.py

Here's a version of #65 with alternate error handling removed (@rbeard0330 sorry, I didn't have write access on your PR). I also made the TemplateSyntaxErrors be raised always.

Remove deepcopy

---

.pre-commit-config.yaml
pyproject.toml

- Add black configurations. related to #36
- Add pre-commit config

Add pre-commit config file

---

.gitignore
README.md
benchmarks/component_rendering.py
django_components/component.py
django_components/templatetags/component_tags.py
tests/test_component.py
tests/test_context.py
tests/test_dependency_rendering.py
tests/test_templatetags.py

Created separate PR for `Component` class refactor.

Refactored Component class

---

.pre-commit-config.yaml
benchmarks/component_rendering.py
django_components/component.py
django_components/component_registry.py
django_components/middleware.py
django_components/template_loader.py
django_components/templatetags/component_tags.py
pyproject.toml
setup.py
tests/django_test_setup.py
tests/test_component.py
tests/test_context.py
tests/test_dependency_rendering.py
tests/test_registry.py
tests/test_templatetags.py
tests/testutils.py

Add a new line to .pre-commit-config.yaml to test pre-commit.ci service in a new pr﻿. related #36

Testing pre-commit.ci service

---

django_components/templatetags/component_tags.py

Fix for #239

---

tests/templates/template_with_slot_in_a_loop.html
tests/test_templatetags.py

Tests for https://github.com/EmilStenstrom/django-components/issues/272.
I'll add a couple more tests, just opening the PR early as [instructed](https://github.com/EmilStenstrom/django-components/issues/272#issuecomment-1517803292) by @lemontheme.

Fix - fill inside loop

---

django_components/component.py
tests/test_templatetags.py

Just a bit more helpful error message when trying to fill invalid slot name - try to guess typos and write a list of unfilled slots.

Invalid slot more helpful message

---

django_components/management/commands/startcomponent.py

Initial pr to add `startcomponent` management command to the package. related #249

[WIP] add `startcomponent` management command

---

README.md

feat(docs): add `startcomponent` docs to the `README.md` file

---

.gitignore
tests/django_test_setup.py
tests/test_startcomponent_command.py

Hi @EmilStenstrom,
This PR addresses #324 and #345 let me know what you think.

Add startcomponent test cases and setup

---

README.md
django_components/component.py
sampleproject/calendarapp/templates/calendarapp/calendar.html
sampleproject/components/greeting.py
tests/test_component.py

Hey @EmilStenstrom,
Sorry for so many PRs 😅. Just found some time and wanted to make progress on this.
Here's the PR for single-file components discussed in #183. The design is slightly different from your proposal, but hopefully still makes sense.
Let me know what you think.
Best,
Dylan

Implement single file components

---

README.md

Hi @EmilStenstrom,
I updated the documentation to close this [issue](https://github.com/EmilStenstrom/django-components/issues/71)
Best,
Dylan

Document ComponentDependencyMiddleware

---

README.md
django_components/app_settings.py
django_components/templatetags/component_tags.py
tests/test_context.py
tests/test_settings.py

Hi @EmilStenstrom,
I created a PR for this [issue](https://github.com/EmilStenstrom/django-components/issues/351), including tests.
Let me know if this is what you had in mind.
Best,
Dylan

Use setting to limit context

---

django_components/template_loader.py
tests/test_autodiscover.py

Hey @EmilStenstrom,
I came across issue #290 and made a quick fix for it, and added tests. Let me know what you think!
Best,
Dylan

Fix for #290

---

README.md

@EmilStenstrom found a bit of time to add the examples to the repo. Let me know what you think of adding this section.

Add django-htmx-components

---

pyproject.toml
src/django_components/__init__.py
src/django_components/app_settings.py
src/django_components/apps.py
src/django_components/component.py
src/django_components/management/commands/startcomponent.py
src/django_components/management/commands/upgradecomponent.py
src/django_components/middleware.py
src/django_components/template_loader.py
src/django_components/templatetags/component_tags.py
src/django_components/types.py
src/django_components/utils.py

Hey 👋 
Following-up on the MR to type the `@register` decorator, I continued to add type hints.
This is quite a lot of changes, so I hope other users can review and test to spot some inaccuracies.
Nb: this PR was made on top of #406, but I can rebase it from the main branch if needed.
Cheers!

feat: full type hints

---

src/django_components/component.py
src/django_components/context.py
src/django_components/slots.py
tests/test_component.py

Closes https://github.com/EmilStenstrom/django-components/issues/453

refactor: fix slot fills for components nested in themselves

---

README.md
src/django_components/component.py
src/django_components/expression.py
src/django_components/slots.py
src/django_components/templatetags/component_tags.py
tests/test_template_parser.py
tests/test_templatetags.py

~Implementation may still change based on feedback.~ This MR is now ready for review, it adds "scoped slot" feature as per https://github.com/EmilStenstrom/django-components/issues/494#issuecomment-2113363070.
I also moved the README sections around a bit, and added a view missing sections. See  the screenshot in https://github.com/EmilStenstrom/django-components/pull/495#discussion_r1598567122 and other comments below.
Closes https://github.com/EmilStenstrom/django-components/issues/494

feat: Scoped slots + Updated docs

---

src/django_components/component.py
tests/templates/block_in_component_parent.html
tests/test_templatetags.py

See https://github.com/EmilStenstrom/django-components/issues/508#issuecomment-2133034148 for context
Closes https://github.com/EmilStenstrom/django-components/issues/508

fix: compat with block tag in django mode

---

src/django_components/component.py

At the depth of 13 nested components, I got  `RecursionError: maximum recursion depth exceeded`. Turns out that it was my own doing, as I was patching the `Template._render` methods to add hooks for before/after render, and the patching logic was called multiple times, nesting the functions onto itself couple of times.
However, since the code I used for the patching was the same as is in this codebase, it's possible that in the codebase we also accidentally call the patching logic more times, which can increase the risk of hitting `RecursionError`.
So this fix just makes sure we don't do so.

fix: do not monkeypatch already patched templates

---

README.md

Add documentation about code highlight on single-file-components as discussed on https://github.com/EmilStenstrom/django-components/discussions/548

Add documentation for jetbrains IDEs

---

src/django_components/component.py
tests/test_component.py

Fixes https://github.com/EmilStenstrom/django-components/issues/580

fix: Set `Context.template` for components to work with include

---

README.md

Closes https://github.com/EmilStenstrom/django-components/issues/646

refactor: fix broken links

---

README.md

An attempt at modernizing the pitch when we're now aiming for practical parity with many frontend frameworks.

Improve pitch in README

---

src/django_components/node.py
tests/test_templatetags.py

Closes https://github.com/EmilStenstrom/django-components/discussions/671

fix: Using empty default fill with no whitespace

---

src/django_components/autodiscovery.py
src/django_components/components/dynamic.py
src/django_components/library.py
src/django_components/template.py
src/django_components/urls.py
src/django_components/util/types.py

Adds documentation here and there

docs: add docstrings

---

src/django_components/app_settings.py

With the code changes out of the way, this MR documents the settings for the documentation site.
Demo:
https://github.com/user-attachments/assets/5b9695f2-8202-4648-87c6-e3b0221ceb58

docs: document settings

---

requirements-ci.txt
requirements-dev.txt
tox.ini

Reverts EmilStenstrom/django-components#769

Revert "build(deps): bump playwright from 1.48.0 to 1.49.0"

---

sampleproject/components/calendar/calendar.py

refactor: fix sampleproject component-relative

---

CHANGELOG.md
README.md
docs/concepts/advanced/authoring_component_libraries.md
docs/overview/community.md
docs/overview/welcome.md

@EmilStenstrom A case for celebration! 🎉 (or at least for me). This is the first working package for django-components :)

docs: add djc-heroicons to community examples

---

CHANGELOG.md
pyproject.toml

chore: bump v0.127

---

src/django_components/component.py
src/django_components/perfutil/component.py
tests/test_component.py

Follow up to https://github.com/django-components/django-components/pull/936, this PR fixes the `on_render_after` hook, so that it:
1. Receives the *fully* rendered HTML. Because after #936, the hook actually receives an HTML that still contains internal placeholders for nested components (e.g. `<template djc-render-id="a1b2c3">`).
2. Also added tests to check that the Context that's passed to `on_render_before` and `on_render_after` contains the same info, which I think is important to check now, because the two hooks are being called from different places in the code.

refactor: fix on_render_after hook

---

docs/overview/installation.md

One char PR. I'll add more if I find more, but so far docs have been great.

Documentation typo

---

docs/guides/devguides/dependency_mgmt.md
docs/guides/devguides/slots_and_blocks.md

Few more formatting and wording changes to the "devguides" docs

refactor: udpate formatting and wording for the "devguides" docs

---

README.md
docs/guides/other/troubleshooting.md
docs/overview/welcome.md
src/django_components/component.py
src/django_components/slots.py

Fix bug that I encountered when preparing the benchmarking test case (mentioned here https://github.com/django-components/django-components/issues/14#issuecomment-2642331396).
I didn't include a test to check for this bug, because, frankly, it's not clear to me under which conditions it occurs. I just know that it happens in my work project. So I'm hoping to implicitly test of it once I add the benchmark tests - as for those, I would also test the final output, and that assertion will test for this behaviour.
Also, I added a few more trace-level logs. 
As I faced another issue with this resolution of slots, I was annoyed, because I already spend ungodly amount of time on that. So I thought - what if we captured enough details in the trace logs so that AI could fix those issues? In other …

refactor: fix bug with complex slots and "django" mode + add docs on debugging with AI agents

---

src/django_components/component_media.py

fix: thread unsafe media resolve validation by moving it to ComponentMedia __post_init

---

tests/test_templatetags_slot_fill.py
tests/test_templatetags_templating.py

Another maintenance / cleanup PR. As I was writing the helper function to get all components ([mentioned here](https://github.com/django-components/django-components/pull/1025#issuecomment-2727405187)), I found that inside the test, the helper function returned like 60 extra components.
Turns out that this is because there's still a lot of tests where the component class is created outside of the test function, and so they are not cleaned up. On the other hand, the components that are defined within test functions wrapped with `@djc_test` are cleaned up properly.
My first approach was to rewrite the tests, so that the component classes are defined within the scope of `@djc_test`. After refactoring two test files, I gave up, because it would be still a lot of work, and there are more …

refactor: refactor tests to create components inside test functions

---

.github/workflows/docs.yml

This should finally fix the workflow to create and push benchmark results on release. See example pipeline run https://github.com/JuroOravec/django-components/actions/runs/13972306859/job/39117024057

refactor: fix docs workflow

---

CHANGELOG.md
pyproject.toml
src/django_components/component_media.py
tests/test_component_media.py

Fixes https://github.com/django-components/django-components/issues/1062

refactor: fix use of URLs in Component.Media

---

.github/workflows/tests.yml
CHANGELOG.md
src/django_components/component_media.py
src/django_components/util/testing.py
tests/components/glob/glob.py
tests/test_component_media.py

Closes https://github.com/django-components/django-components/discussions/1073 and https://github.com/django-components/django-components/issues/1074

refactor: Fix path resolution relative to COMPONENTS.dirs + add CI test to ensure sampleproject works

---

docs/concepts/fundamentals/component_views_urls.md
src/django_components/extensions/view.py

Closes https://github.com/django-components/django-components/issues/1114

docs: document how to access component instance from within View

---

pyproject.toml

build: Change versioning to major.minor.patch

---

docs/concepts/fundamentals/http_request.md
docs/concepts/fundamentals/render_api.md
src/django_components/component.py

This updates the page on working with the request object.
And I also added docstring to `Component.input`
https://github.com/user-attachments/assets/405a2fa7-798e-4350-acc3-8fd504b58c70

docs: update section on working with request object

---

src/django_components/util/misc.py
tests/test_component_view.py

See https://github.com/django-components/django-components/pull/1160#pullrequestreview-2813312003

refactor: update impl of format_url

---

src/django_components/component.py
src/django_components/slots.py
tests/test_benchmark_djc.py

refactor: slots cleanup

---

docs/getting_started/components_in_templates.md

59f8230 --> file name changed(authoring_component_libraries  -> compnent_libraries)

docs: fix component_library link

---

CHANGELOG.md
pyproject.toml
src/django_components/slots.py
tests/templates/extends_compat_c_include.html
tests/templates/extends_compat_d_extended.html
tests/test_templatetags_extends.py

Fix for https://github.com/django-components/django-components/issues/1325

fix: fix compat with extends and includes

---

docs/scripts/reference.py
src/django_components/commands/list.py
src/django_components/component_media.py
src/django_components/tag_formatter.py
src/django_components/util/testing.py
tests/test_benchmark_django.py
tests/test_benchmark_djc.py
tests/test_component.py
tests/test_expression.py
tests/test_tag_parser.py

Few linter errors blocking https://github.com/django-components/django-components/pull/1370.

refactor: ruff - underscore unused vars
